### ISSUE TITLE
Lots more food(ADDON) 

### ISSUE THREAD

**Issue by Sniffles98** [legopitstop/addons#5]
### Describe the bug

The tomato seeds are not planting on the fertile soil like it should

### Steps To Reproduce

1. Put down soil
2. Get tomato seeds
3. Click to plant on soil
...

### Expected behavior

I expected it to plant it on the fertile soil like it should

### Minecraft Version

1.20

### Mod Version

Bedrock 

### Platform

Xbox, playstation,phones(android),switch, laptop (window 10/11)

**Comment by legopitstop** [comment]
Closed as bugs related to Lot's More Food are tracked via the Lot's More Food repo: https://github.com/legopitstop/Lots-More-Food-Mods/issues
