### ISSUE TITLE
[Ultimate Block Breaker] Not showing up

### ISSUE THREAD

**Issue by Tezarak** [legopitstop/addons#6]
### What Addon are you using?

Ultimate Block Breaker

### Describe the bug

I'm fairly new to Addons so I feel I could be missing something obvious. It's not showing up when I have added it as a resource and behavior pack in my realm.

### Steps To Reproduce

1.
2.
3.
...

### Expected behavior

Squash the bug or talk me through a fix

### Minecraft Version

1.20.51

### Addon Version

1.2.0

### Platform

Windows 10

**Comment by legopitstop** [comment]
This is an issue on your side and not with the addon. Make sure you enable Holiday Creator Features on the world before uploading it to your realm.

**Comment by Tezarak** [comment]
Eye all the experimental features are on. When I search breaker in the menu I only get the upgrades though
