### ISSUE TITLE
(More Stairs and Slabs [moress]) Archive upload somewhere?

### ISSUE THREAD

**Issue by TanjunPuran** [legopitstop/addons#7]
### Describe the solution you'd like

An archive of the old version of More stairs and slabs [moress] addon.

### Additional context

Even though the old version was broken slightly it still was amazing in its own ways. One day I lost my packs and wanted the more stairs and slabs back. So, I tried to get it on mcpedl via your profile just to find out it was deleted. (I checked other places too)
You said you'll add more blocks into your new pack in the future. Which im excited for but I think it would be nice to have an archive of the old version still though, so while we wait we could use it.
I understand if you dont want to do this.
"More Stairs and Slabs! Pack by: Legopitstop" image:
![pack_icon](https://github.com/user-attachments/assets/1b354715-5fa3-44da-90dc-f8a7ef14a6f2)

**Comment by legopitstop** [comment]
You can find all archives from 1.0.0 (first release) to 1.5.0 (latest release) on curseforge, where I post my add-ons now. https://www.curseforge.com/minecraft-bedrock/addons/more-block/files/all
